# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'qiita_hackathon' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for qiita_hackathon
  pod 'R.swift' , '~> 7'
  pod 'KeychainAccess' , '~> 4'
  pod 'APIKit' , '~> 5'

  target 'qiita_hackathonTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'qiita_hackathonUITests' do
    # Pods for testing
  end

end
